### ISSUE TITLE
Support for multiple LLM services in Co-op Translator

### ISSUE THREAD

**Issue by skytin1004** [Azure/co-op-translator#56]
### Describe the feature you'd like

We plan to support additional large language model (LLM) and translation services beyond Azure OpenAI, allowing users the flexibility to select and integrate the LLM provider of their choice.

Additionally, we are considering implementing a markdown-only translation feature for users who may lack an Azure Computer Vision key or prefer to focus exclusively on markdown translation. This new functionality would let users translate markdown content while retaining original images in place, providing a streamlined translation experience. The `-md` command will be updated to enable this selective translation mode.

(Currently the `-md` command updates the markdown link to link to translated images.)
  
While image translation may rely on specific services like Azure Computer Vision, we aim to make markdown translation more adaptable and accessible to users, regardless of their backend service preference. 

### Additional context

This feature would significantly enhance the versatility of Co-op Translator, making it more attractive to developers and organizations beyond those using Microsoft Azure. An example of implementation could include a "TranslationService" interface that supports multiple backends, enabling the user to specify their desired provider via a configuration parameter.

### Are you willing to submit a pull request to implement this feature?

- [x] I am willing to submit a pull request

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by skytin1004** [comment]
Hi @1044197988, Thank you for interest!

I plan to implement this feature by December 20th. Initially, I will integrate OpenAI models and then ensure that the implementation is flexible enough to support additional LLMs.

Since this project is part of Azure Open-Source Software (OSS), I plan to consult with the Microsoft team involved in the project before adding models other than OpenAI models.

**Comment by skytin1004** [comment]
Hi @1044197988, I've just finished designing the system to allow flexible addition of LLMs, and I've modified it to work with just the **OpenAI** environment variables for now. Adding new LLMs is now much easier. If multilingual support is needed, I'm open to adding other language models as well. If you have any specific models in mind, feel free to suggest them!

**Comment by 1044197988** [comment]
Thank you very much, this feature was completed very promptly. Currently, OpenAI is very suitable and there are no other requirements at the moment. Thank you again and I am looking forward to future work.
